apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-networkpolicy
  namespace: {{ .Release.Name }}
  labels:
       {{- include "application.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              env: {{ .Values.environment.name }}
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.monitoring.namespace }}
        - podSelector: {}
