apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm 
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  GRACEFUL_TIME: {{ .Values.configmap.gracefulTime | quote }}
  APP_PORT: {{ quote  .Values.configmap.appPort }}
