apiVersion: v1
kind: LimitRange
metadata:
  name: limit-cpu-memory
  namespace: {{ .Release.Name }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 2 }}
