environment:
  name: desarrollo

namespace:  
  annotations: 
    openshift.io/node-selector: "env={{ .Values.environment.name }}"

egress:
  dnsAllows: []
  cidrAllows: []
  cidrDenies:
    - 0.0.0.0/0
limitRange:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 512Mi
      cpu: 100m
    max:
      memory: 1Gi
      cpu: 500m
    min:
      memory: 100Mi
      cpu: 10m
    type: Container
monitoring:
  namespace: openshift-monitoring
jenkins:
  serviceAccount:
    name: jenkins
    namespace: shared-jenkins
